name: build

on:
  push:
    paths:
      - ".github/workflows/build.yml"
      - "src/TodoApi/**"
  workflow_dispatch: # manual

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/TodoApi
    steps:
      - uses: actions/checkout@v4
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
      - run: dotnet test
        working-directory: ./tests/TodoApi.Tests
